name: Publish to PyPi on Release

on:
  push:
    branches: [ main, master ]
  pull_request:
  release:
    types: [ published, edited ]  # fires when you publish or edit a GitHub Release

jobs:
  release-build:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # hatch-vcs needs tags
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build sdist/wheel
        run: |
          python -m pip install --upgrade pip
          pip install build hatchling hatch-vcs
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    # Only run on GitHub Release events that are NOT prereleases
    if: github.event_name == 'release' && github.event.release.prerelease == false
    needs:
      - release-build
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: dist/
